/**
 * Demo data seeding (W3 T190-T192, DFS-002/003/004).
 *
 * Seeds a single owned/generated demo Track so a new user can experience the
 * sentence-level learning loop WITHOUT a provider key, a media import, or any
 * terminal step. The demo uses:
 *   - bundled synthetic audio (public/demo/demo-listening.mp3) — no copyright;
 *   - a bundled sentence timeline — no provider transcription call;
 *   - Track.trackType = "DEMO" ownership marker (W0-D T042) so demo data is
 *     distinguishable and removable without touching personal records.
 *
 * Provenance: audio is generated by FFmpeg lavfi (sine wave), timeline is
 * hand-authored. See public/demo/PROVENANCE.md.
 *
 * Idempotent: re-seeding is safe and never duplicates.
 */
import { prisma as defaultPrisma } from "@/lib/prisma";
import type { PrismaClient } from "@prisma/client";

/** The ownership marker stored on Track.trackType for demo records. */
export const DEMO_TRACK_TYPE = "DEMO";

/** Bundled demo audio URL (served from public/demo, immutable). */
export const DEMO_AUDIO_URL = "/demo/demo-listening.mp3";

/** Stable id for the demo track so seeding is idempotent. */
export const DEMO_TRACK_ID = "demo-listening-001";

/** The bundled sentence timeline for the demo track. */
const DEMO_SENTENCES: Array<{ text: string; start: number; end: number }> = [
  { text: "Welcome to DeepListener. Listen carefully.", start: 0, end: 2.5 },
  { text: "Try to catch every word without reading.", start: 2.5, end: 5.0 },
];

export interface DemoSeedResult {
  seeded: boolean;
  trackId: string;
  sentenceCount: number;
}

/** Resolve the active Prisma client (overridable for tests). */
function client(override?: PrismaClient): PrismaClient {
  return override ?? defaultPrisma;
}

/**
 * Seed the demo track if it does not already exist. Idempotent: a second call
 * is a no-op and returns `{ seeded: false }` with the existing track id.
 *
 * Re-seeding also restores a demo that was archived or had its sentences
 * removed, so the "re-seed demo" affordance always returns a usable demo:
 *   - resets isArchived back to false;
 *   - recreates any missing bundled sentences.
 *
 * Never touches personal tracks, sentences, or review items (DFS-004).
 */
export async function seedDemoTrack(db?: PrismaClient): Promise<DemoSeedResult> {
  const prisma = client(db);
  const existing = await prisma.track.findUnique({
    where: { id: DEMO_TRACK_ID },
    include: { sentences: true },
  });
  if (existing) {
    // Restore the demo so it is always usable after re-seed: un-archive it
    // and recreate any missing bundled sentences.
    const existingTexts = new Set(existing.sentences.map((s) => s.text));
    const missingSentences = DEMO_SENTENCES.filter((s) => !existingTexts.has(s.text));

    await prisma.track.update({
      where: { id: existing.id },
      data: {
        isArchived: false,
        ...(missingSentences.length > 0
          ? {
              sentences: {
                create: missingSentences.map((s, index) => ({
                  text: s.text,
                  startTime: s.start,
                  endTime: s.end,
                  // Place recreated sentences after the existing ones.
                  orderIndex: existing.sentences.length + index,
                })),
              },
            }
          : {}),
      },
    });

    return {
      seeded: false,
      trackId: existing.id,
      sentenceCount: existing.sentences.length + missingSentences.length,
    };
  }

  const track = await prisma.track.create({
    data: {
      id: DEMO_TRACK_ID,
      title: "DeepListener Demo — Blind Listening",
      audioUrl: DEMO_AUDIO_URL,
      mediaType: "AUDIO",
      transcription: JSON.stringify(
        DEMO_SENTENCES.map((s) => ({ text: s.text, start: s.start, end: s.end })),
      ),
      trackType: DEMO_TRACK_TYPE,
      trackTopic: "demo",
      status: "UNLEARNT",
      sentences: {
        create: DEMO_SENTENCES.map((s, index) => ({
          text: s.text,
          startTime: s.start,
          endTime: s.end,
          orderIndex: index,
        })),
      },
    },
    include: { sentences: true },
  });

  return { seeded: true, trackId: track.id, sentenceCount: track.sentences.length };
}

/**
 * Remove ALL demo-owned records (Track.trackType = DEMO_TRACK_TYPE) and their
 * cascaded sentences/review items, WITHOUT touching personal tracks.
 *
 * Returns the count of removed demo tracks. Personal records are guaranteed
 * unchanged because the delete is scoped by trackType (DFS-004).
 */
export async function removeDemoTracks(db?: PrismaClient): Promise<{ removedTracks: number }> {
  const prisma = client(db);
  const result = await prisma.track.deleteMany({
    where: { trackType: DEMO_TRACK_TYPE },
  });
  return { removedTracks: result.count };
}

/** Whether any demo track currently exists. */
export async function demoTrackExists(db?: PrismaClient): Promise<boolean> {
  const prisma = client(db);
  const count = await prisma.track.count({ where: { trackType: DEMO_TRACK_TYPE } });
  return count > 0;
}
